### Http Requests ###
@hostname = localhost
@port = 8001
@contextPath = /api
@basePath = http://{{hostname}}:{{port}}{{contextPath}}

### Health Check ###
GET {{basePath}}/health HTTP/1.1

### Animals ###
### Get all animals
GET {{basePath}}/animals HTTP/1.1

### Get animal by id
GET {{basePath}}/animals/DF2D8409-1BA3-450F-AF81-5951ABAE424B HTTP/1.1

### Breeds ###
### Get all breeds
GET {{basePath}}/breeds HTTP/1.1